services:
  db:
    image: postgis/postgis:17-master
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/
      # set shared memory limit
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: dietiestatesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASSWORD
      PGDATA: /var/lib/postgresql/17/docker
    secrets:
      - DB_PASSWORD

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dietiestatesdb
      DB_USER: admin
    volumes:
      - ~/.aws:/root/.aws:ro
    secrets:
      - DB_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

volumes:
  pgdata:

secrets:
  DB_PASSWORD:
    file: ./secrets/postgres-passwd.txt
  AWS_ACCESS_KEY_ID:
    file: ./secrets/aws-access-key-id.txt
  AWS_SECRET_ACCESS_KEY:
    file: ./secrets/aws-secret-access-key.txt