spring:
  application:
    name: DietiEstatesBackend
  config:
    import: "optional:configtree:/run/secrets/"

  datasource:
    url: jdbc:postgresql://dietiestatesdb.c3k82uiuwokm.eu-west-3.rds.amazonaws.com:5432/dietiestatesdb
    driver-class-name: org.postgresql.Driver
    username: dietiestatesdba
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration/

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        spatial.connection_finder: org.hibernate.spatial.dialect.postgis.PostgisDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_tKWUxvA4t
          jwk-set-uri: https://cognito-idp.eu-west-3.amazonaws.com/eu-west-3_tKWUxvA4t/.well-known/jwks.json

  threads:
    virtual:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /api

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION:eu-west-3}

frontend:
  url: ${FRONTEND_URL:http://localhost:4200}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
